### ISSUE TITLE
Vector 사용하기, null 문자 전송 안하는 문제 수정

### ISSUE THREAD

**Issue by Dull-Dull** [ath331/aa#5]
4일동안 진전이 없다니!!!!

내가 말했던건 어디까지 진행됐음???

그리고 strcat 으로 null 문자 를 붙인다는 발상은 완전히 잘못된 발상이므로 수정하시오

strcat 으로 null 문자가 없는 문자열에 null 문자를 를 붙이려고 할 때 생기는 문제를 이 이슈에 정리해서 댓글 남겨주면 좋겠음

그리고 https://www.gitignore.io/ 이 홈페이지 제발좀 들어가서 설정좀 보시오

**Comment by Dull-Dull** [comment]
@ath331  태그남기기!!

**Comment by ath331** [comment]
@Dull-Dull 방금 채팅성공해서 푸시해놨습니다 ㅎㅎ 허접한 수준이지만 그래도 이제 '채팅'이라고 부를수는 있어요
